"""empty message

Revision ID: 2701a8bd3772
Revises: 
Create Date: 2022-07-31 14:46:54.889499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2701a8bd3772'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('day_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('quote', sa.String(), nullable=True),
    sa.Column('quote_author', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('day_id')
    )
    op.create_table('entry',
    sa.Column('entry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('memo', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('mood_score', sa.Float(), nullable=False),
    sa.Column('activities', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('emotions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day.day_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry')
    op.drop_table('day')
    # ### end Alembic commands ###
