"""empty message

Revision ID: 4af6d1443899
Revises: 2701a8bd3772
Create Date: 2022-08-05 13:53:35.456510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af6d1443899'
down_revision = '2701a8bd3772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day', sa.Column('time_stamp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day', 'time_stamp')
    # ### end Alembic commands ###
