"""empty message

Revision ID: 5f2ba52f70d3
Revises: 
Create Date: 2022-08-09 15:17:28.541201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2ba52f70d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('month',
    sa.Column('month_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('this_year', sa.String(), nullable=False),
    sa.Column('this_month', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('month_id')
    )
    op.create_table('day',
    sa.Column('day_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('month_string', sa.String(), nullable=False),
    sa.Column('quote', sa.String(), nullable=True),
    sa.Column('quote_author', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['month_id'], ['month.month_id'], ),
    sa.PrimaryKeyConstraint('day_id')
    )
    op.create_table('entry',
    sa.Column('entry_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('memo', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('mood_score', sa.Float(), nullable=False),
    sa.Column('activities', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('emotions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day.day_id'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry')
    op.drop_table('day')
    op.drop_table('month')
    # ### end Alembic commands ###
