"""empty message

Revision ID: e63918b36a12
Revises: 833479a9be3f
Create Date: 2022-07-28 21:22:25.928669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63918b36a12'
down_revision = '833479a9be3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day', sa.Column('quote_author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day', 'quote_author')
    # ### end Alembic commands ###
