"""empty message

Revision ID: fc1d83fdd1ae
Revises: 4af6d1443899
Create Date: 2022-08-05 13:58:09.606863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1d83fdd1ae'
down_revision = '4af6d1443899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day', 'time_stamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day', sa.Column('time_stamp', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
